In [ ]:
import pandas as pd

In [ ]:
###
1. # pip install pandas
2. # % pip install pandas
3. # !pip install pandas

3.0

In [ ]:
df = pd.read_csv('/content/student_life.csv')

In [ ]:
df.head() # => boshidan 5 tasini olib beradi

     학번  학년 성별  스마트폰   수면    학점
0  S001   1  여   4.2  8.0  2.91
1  S002   4  여   4.1  6.6  3.14
2  S003   3  여   5.1  7.7  3.43
3  S004   4  남   4.5  6.4  3.34
4  S005   3  여   4.1  6.9  3.04

In [ ]:
df.tail() # oxiridan 5 ta column bilan rowni chiqarib beradi

       학번  학년 성별  스마트폰   수면    학점
195  S196   3  남   2.7  7.7  3.48
196  S197   1  여   4.9  6.7  3.74
197  S198   2  여   4.3  5.3  3.39
198  S199   1  여   6.9  7.0  3.16
199  S200   4  여   2.7  6.4  3.30

In [ ]:
df.nunique() # xar bir ustundagi klasslar soni

학번      200
학년        4
성별        2
스마트폰     62
수면       40
학점      108
dtype: int64

In [ ]:
df['학번'] # o'sha aynan o'ziga tegishli qismdagi ma'lumotlarni chiqarib beradi

0      S001
1      S002
2      S003
3      S004
4      S005
       ...
195    S196
196    S197
197    S198
198    S199
199    S200
Name: 학번, Length: 200, dtype: object

In [ ]:
df[['학번','수면']]

       학번   수면
0    S001  8.0
1    S002  6.6
2    S003  7.7
3    S004  6.4
4    S005  6.9
..    ...  ...
195  S196  7.7
196  S197  6.7
197  S198  5.3
198  S199  7.0
199  S200  6.4

[200 rows x 2 columns]

In [ ]:
df.info() # data haqida umumiy ma'lumot olish

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   학번      200 non-null    object
 1   학년      200 non-null    int64
 2   성별      200 non-null    object
 3   스마트폰    196 non-null    float64
 4   수면      200 non-null    float64
 5   학점      200 non-null    float64
dtypes: float64(3), int64(1), object(2)
memory usage: 9.5+ KB

In [ ]:
df.isnull().sum()

학번      0
학년      0
성별      0
스마트폰    4
수면      0
학점      0
dtype: int64

In [ ]:
df.isnull().any()

학번      False
학년      False
성별      False
스마트폰     True
수면      False
학점      False
dtype: bool

CONDITIONS

In [ ]:
# agar son musbat bo'lsa positive aks xolda negative

In [ ]:
son = 0
if son > 0:
     print('positive')
elif son < 0:
      print('negative')
else:
    print('nolga teng')

nolga teng

In [ ]:
baxo = 4
if baxo == 5:
  print("A'lo")
elif baxo == 4:
  print("Yaxshi")
elif baxo == 3:
  print("Qoniqarsiz")
else:
  print('Xatolik bor yoki juda yomon')

Yaxshi

VAZIFA

In [41]:
# Imtixondan o'tishni nazorat qilish uchun  condition tuzing
score=29
if score <0:
  print('Xatolik bor')
elif score < 30:
  print("Imtihondan yiqildingiz")
elif score < 50:
  print('Qoniqarli')
elif score < 80:
  print('Yaxshi')
else:
  print('A\'lo')

Imtihondan yiqildingiz

In [42]:
# Pasport olish uchun condition tuzing
yosh = 17
passportBerilsinmi = True
if yosh < 17:
  passportBerilsinmi = False
else:
  passportBerilsinmi= True

if passportBerilsinmi == True:
  print('Pasport berilsin')
else:
  print('Pasport berilmasin')

Pasport berilsin