DATA BILAN TANISHUV

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('ai-impact-jobs-layoff-risk-dataset.csv')
df

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,Master's,6,Finance,Accountant,Medium,Entry,84,21,94,Medium,5,7,40,26,High
1,44,Master's,14,Manufacturing,Production Supervisor,Small,Entry,30,84,68,Low,2,2,14,9,Low
2,36,Bachelor's,7,Retail,Store Manager,Medium,Senior,12,86,71,Low,0,1,6,3,Low
3,27,Bachelor's,6,Finance,Auditor,Large,Entry,90,18,21,Medium,3,10,67,26,High
4,49,High School,12,Finance,Auditor,Small,Entry,49,52,72,Medium,5,13,26,19,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,56,Bachelor's,10,Retail,Sales Associate,Small,Entry,29,62,44,Low,0,4,16,0,Medium
19996,43,Bachelor's,9,Manufacturing,Production Supervisor,Medium,Entry,87,20,20,High,9,23,77,67,High
19997,28,High School,7,Telecom,Support Specialist,Medium,Entry,91,2,49,Medium,2,14,55,10,High
19998,46,Bachelor's,3,Manufacturing,Quality Engineer,Medium,Senior,76,40,89,Medium,3,13,66,5,Medium
19999,36,Bachelor's,5,Retail,Store Manager,Medium,Mid,45,65,75,Low,1,0,30,8,Medium

In [5]:
df.head()

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
0,59,Master's,6,Finance,Accountant,Medium,Entry,84,21,94,Medium,5,7,40,26,High
1,44,Master's,14,Manufacturing,Production Supervisor,Small,Entry,30,84,68,Low,2,2,14,9,Low
2,36,Bachelor's,7,Retail,Store Manager,Medium,Senior,12,86,71,Low,0,1,6,3,Low
3,27,Bachelor's,6,Finance,Auditor,Large,Entry,90,18,21,Medium,3,10,67,26,High
4,49,High School,12,Finance,Auditor,Small,Entry,49,52,72,Medium,5,13,26,19,Medium

In [6]:
df.tail()

,Age,Education_Level,Years_of_Experience,Industry,Job_Role,Company_Size,Job_Level,Routine_Task_Percentage,Creativity_Requirement,Human_Interaction_Level,AI_Adoption_Level,Number_of_AI_Tools_Used,AI_Usage_Hours_Per_Week,Tasks_Automated_Percentage,AI_Training_Hours,Layoff_Risk
19995,56,Bachelor's,10,Retail,Sales Associate,Small,Entry,29,62,44,Low,0,4,16,0,Medium
19996,43,Bachelor's,9,Manufacturing,Production Supervisor,Medium,Entry,87,20,20,High,9,23,77,67,High
19997,28,High School,7,Telecom,Support Specialist,Medium,Entry,91,2,49,Medium,2,14,55,10,High
19998,46,Bachelor's,3,Manufacturing,Quality Engineer,Medium,Senior,76,40,89,Medium,3,13,66,5,Medium
19999,36,Bachelor's,5,Retail,Store Manager,Medium,Mid,45,65,75,Low,1,0,30,8,Medium

In [7]:
df.nunique()

Age                            40
Education_Level                 4
Years_of_Experience            27
Industry                        8
Job_Role                       24
Company_Size                    3
Job_Level                       3
Routine_Task_Percentage        85
Creativity_Requirement        101
Human_Interaction_Level        80
AI_Adoption_Level               3
Number_of_AI_Tools_Used        11
AI_Usage_Hours_Per_Week        31
Tasks_Automated_Percentage     90
AI_Training_Hours              80
Layoff_Risk                     3
dtype: int64

In [8]:
df['AI_Usage_Hours_Per_Week'].nunique()

31

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 16 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Age                         20000 non-null  int64
 1   Education_Level             20000 non-null  str
 2   Years_of_Experience         20000 non-null  int64
 3   Industry                    20000 non-null  str
 4   Job_Role                    20000 non-null  str
 5   Company_Size                20000 non-null  str
 6   Job_Level                   20000 non-null  str
 7   Routine_Task_Percentage     20000 non-null  int64
 8   Creativity_Requirement      20000 non-null  int64
 9   Human_Interaction_Level     20000 non-null  int64
 10  AI_Adoption_Level           20000 non-null  str
 11  Number_of_AI_Tools_Used     20000 non-null  int64
 12  AI_Usage_Hours_Per_Week     20000 non-null  int64
 13  Tasks_Automated_Percentage  20000 non-null  int64
 14  AI_Training_Hours           20000 non-null  int64
 15  Layoff_Risk                 20000 non-null  str
dtypes: int64(9), str(7)
memory usage: 2.4 MB

In [10]:
df.isnull().sum()

Age                           0
Education_Level               0
Years_of_Experience           0
Industry                      0
Job_Role                      0
Company_Size                  0
Job_Level                     0
Routine_Task_Percentage       0
Creativity_Requirement        0
Human_Interaction_Level       0
AI_Adoption_Level             0
Number_of_AI_Tools_Used       0
AI_Usage_Hours_Per_Week       0
Tasks_Automated_Percentage    0
AI_Training_Hours             0
Layoff_Risk                   0
dtype: int64

In [11]:
df.isnull().any()

Age                           False
Education_Level               False
Years_of_Experience           False
Industry                      False
Job_Role                      False
Company_Size                  False
Job_Level                     False
Routine_Task_Percentage       False
Creativity_Requirement        False
Human_Interaction_Level       False
AI_Adoption_Level             False
Number_of_AI_Tools_Used       False
AI_Usage_Hours_Per_Week       False
Tasks_Automated_Percentage    False
AI_Training_Hours             False
Layoff_Risk                   False
dtype: bool

CONDITIONS

In [5]:
a = 4
if a < 0:
    print("Yomon")
elif a>0:
    print("Yaxshi")
else:
    print('Nol')

Yaxshi

CONDITION HOMEWORKS

In [ ]:
# # Imtihondan o'tish uchun condition

# score = 95

# if 100 > score >=90:
#     print('5 baho bilan o\'tdingiz')
# elif 90 > score >=76:
#     print('4 baho bilan o\'tdingiz')
# elif 76 > score >=60:
#     print("3 baho bilan bilan o'\tdingiz")
# elif 60 > score >= 50:
#     print("2 baho afsuski o'ta olmadingiz")
# else:
#     print("Xatolik")

5 baho bilan o'tdingiz

In [19]:
# Passport uchun condition
age = 16
if age <= 16:
    print("Passport olishingiz mumkin emas. Hali yosh ekansiz")
elif age > 100:
    print("Passport olishingiz mumkin emas. Yoshiz juda katta ekan")
else:
    print('Passport olishingiz mumkin')

Passport olishingiz mumkin emas. Hali yosh ekansiz